services:

#  mongo:
#    image: mongo:4.2
#    hostname: mongo
#    container_name: mongo
#    ports:
#      - 27017:27017
#    environment:
#      MONGO_INITDB_DATABASE: miniautorizador
#      MONGO_INITDB_ROOT_USERNAME: user
#      MONGO_INITDB_ROOT_PASSWORD: password
#    volumes:
#      - ./scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    hostname: mysql
    container_name: mysql
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: miniautorizador
      MYSQL_ROOT_PASSWORD: miniautorizador
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-ma:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pminiautorizador" ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data

    volumes:
      - kafka_data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
  miniautorizador:
    # Rode com minha imagem do docker hub(https://hub.docker.com/r/darlankenobi/miniautorizador)
    #image: darlankenobi/miniautorizador:1.0.0

    # Rode apontando para dockerfile
    build:
       context: ..
       dockerfile: Dockerfile

    container_name: miniautorizador
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=miniautorizador
      - KAFKA_HOST=kafka
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started



volumes:
  db-ma:
    driver: local
  kafka_data:
    driver: local